name: Publish
on:
  push:
    branches:
      - main 
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get secrets
      run: |
        cd config
        mkdir secrets
        echo "${{ secrets.crowdin_key }}" > secrets/crowdin_key.txt

    - name: esbuild
      run: |
        npm i
        npm run-script build
        # Remove gitignore rule for public folder
        sed -i 's/public\///' .gitignore

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: cloverleaf.app
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
